### ISSUE TITLE
Error in const faiss::IndexIVF* faiss::ivflib::extract_index_ivf(const faiss::Index*)

### ISSUE THREAD

**Issue by ksdihgfmata** [facebookresearch/ParlAI#4537]
Hello,
I want to add my own documents to a model using dens_embeddings.
For this, I have created an index as described here https://parl.ai/docs/agent_refs/rag.html .
Unfortunately, I now encounter the following error message.

~/ParlAI$ sudo python3 -m parlai interactive -mf zoo:hallucination/bart_rag_token/model --path-to-index parlai/embeddings/KU_embeddings/HNSW32.index --path-to-dense-embeddings parlai/embeddings/KU_embeddings/out --path-to-dpr-passages parlai/embeddings/doks/KU_test.tsv --retriever-embedding-size 768
08:28:44 | Overriding opt["model_file"] to ~/ParlAI/data/models/hallucination/bart_rag_token/model (previously: /checkpoint/kshuster/projects/wizard_2.0/parlai_sweeps/take2_bart_sweep44_Sat_Mar_27/cb8/model.oss)
08:28:44 | Overriding opt["path_to_index"] to parlai/embeddings/KU_embeddings/HNSW32.index (previously: zoo:hallucination/wiki_index_compressed/compressed_pq)
08:28:44 | Overriding opt["path_to_dense_embeddings"] to parlai/embeddings/KU_embeddings/out (previously: None)
08:28:44 | Overriding opt["path_to_dpr_passages"] to parlai/embeddings/doks/KU_test.tsv (previously: zoo:hallucination/wiki_passages/psgs_w100.tsv)
08:28:44 | Using CUDA
08:28:44 | loading dictionary from ~/ParlAI/data/models/hallucination/bart_rag_token/model.dict
08:28:44 | num words = 50264
08:28:44 | Rag: full interactive mode on.
08:28:50 | Loading index from parlai/embeddings/KU_embeddings/HNSW32.index
08:28:50 | Loaded index of type <faiss.swigfaiss.IndexHNSWFlat; proxy of <Swig Object of type 'faiss::IndexHNSWFlat ' at 0x7f44a4ee3540> > and size 8
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/ParlAI/parlai/main.py", line 18, in
main()
File "/ParlAI/parlai/main.py", line 14, in main
superscript_main()
File "/ParlAI/parlai/core/script.py", line 325, in superscript_main
return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
File "/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
return script.run()
File "/ParlAI/parlai/scripts/interactive.py", line 118, in run
return interactive(self.opt)
File "/ParlAI/parlai/scripts/interactive.py", line 84, in interactive
agent = create_agent(opt, requireModelExists=True)
File "/ParlAI/parlai/core/agents.py", line 468, in create_agent
model = create_agent_from_opt_file(opt)
File "/home/marie/ParlAI/parlai/core/agents.py", line 421, in create_agent_from_opt_file
return model_class(opt_from_file)
File "/home/marie/ParlAI/parlai/agents/rag/rag.py", line 186, in init
self._generation_agent.init(self, opt, shared) # type: ignore
File "/ParlAI/parlai/agents/bart/bart.py", line 72, in init
super().init(opt, shared)
File "/ParlAI/parlai/core/torch_generator_agent.py", line 485, in init
self.model = fsdp_utils.fsdp_wrap(self.build_model())
File "/ParlAI/parlai/agents/rag/rag.py", line 362, in build_model
model = self._generation_agent.build_rag_model(self.opt, self.dict)
File "/home/marie/ParlAI/parlai/agents/rag/rag.py", line 75, in build_rag_model
return RagModel(opt, dictionary)
File "/ParlAI/parlai/agents/rag/modules.py", line 84, in init
self.retriever = retriever_factory(opt, dictionary, shared=retriever_shared)
File "/ParlAI/parlai/agents/rag/retrievers.py", line 1483, in retriever_factory
return DPRRetriever(opt, dictionary, shared=shared)
File "/ParlAI/parlai/agents/rag/retrievers.py", line 605, in init
self.load_index(opt, shared)
File "/ParlAI/parlai/agents/rag/retrievers.py", line 621, in load_index
self.indexer.deserialize_from(index_path, embeddings_path)
File "/ParlAI/parlai/agents/rag/indexers.py", line 408, in deserialize_from
self.index_ivf = self.faiss.extract_index_ivf(self.index)
File "/usr/local/lib/python3.8/dist-packages/faiss/swigfaiss.py", line 5362, in extract_index_ivf
return _swigfaiss.extract_index_ivf(args)
RuntimeError: Error in const faiss::IndexIVF faiss::ivflib::extract_index_ivf(const faiss::Index) at /project/faiss/faiss/IVFlib.cpp:79: Error: 'ivf' failed

I am glad to hear from you and hope you can help me further.

**Comment by stephenroller** [comment]
This seems like something wrong with your FAISS installation

**Comment by ksdihgfmata** [comment]
When I install Faiss this is what I get: 


UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - faiss-cpu -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - faiss-cpu -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - python=3.9 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31

What am I doing wrong here?

**Comment by mojtaba-komeili** [comment]
I remember having similar issues with FAISS installation. The problem was resolved when I tried installing FAISS through conda instead of pip. I have seen a couple of other cases that pip install of FAISS generates odd errors that conda install deosn't.

**Comment by ksdihgfmata** [comment]
Hello, 
thank you for the answers. Now I get this error.
RuntimeError: Error in const faiss::IndexIVF* faiss::ivflib::extract_index_ivf(const faiss::Index*) at /root/miniconda3/conda-bld/faiss-pkg_1641228905850/work/faiss/IVFlib.cpp:79: Error: 'ivf' failed
I have reinstalled everything and recreated the embeddings file, as well as the index HNSW. However, I still get this error. 
I also installed Faiss with conda.

**Comment by klshuster** [comment]
what is your faiss version?

would you also mind sharing your exact commands for 1) generating the embeddings file, and 2) generating the index? It would also help to know some stats regarding your `.tsv` file --> how many lines? what does a small sample look like?

**Comment by farnazgh** [comment]
For me, it was fixed by adding the indexer type in the command.

**Comment by klshuster** [comment]
ahh yes, if you built a dense index, it is important to specify that, as the default is a compressed IVF one
